version: '3'
services:
  node:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd frontend-react && yarn start"
    ports:
      - "3000:3000"

  backend-rust:
    build: 
      context: ./backend/backend-rust
      dockerfile: Dockerfile
    ports:
      - "8765:8765"