version: '3'
services:
  node:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd frontend-react && yarn start"
    ports:
      - "3000:3000"

  backend-rust:
    build: 
      context: ./backend/backend-rust
      dockerfile: Dockerfile
    ports:
      - "8765:8765"

  db:
    image: postgres:latest
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data